### ISSUE TITLE
Could not find a declaration file for module 'react-tag-cloud'

### ISSUE THREAD

**Issue by hectoraldairah** [IjzerenHein/react-tag-cloud#14]
Hi!
I'm trying to use the component in my project with create-react-app. When I install the dependency vs code shows me:

Could not find a declaration file for module 'react-tag-cloud'. '~/node_modules/react-tag-cloud/dist/TagCloud.js' implicitly has an 'any' type.
  Try `npm install @types/react-tag-cloud` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-tag-cloud'

React doesn't show me an error but the component is not rendered at all.

What can I do? 
What is a .d.ts file?

**Comment by zerobell-lee** [comment]
Same for me. It doesn't work and just render empty div.

**Comment by CGagnier** [comment]
I have the same error as both of you. 

I managed to get it work by including the following classes and include the css file from the example presented in the [README.md](https://github.com/IjzerenHein/react-tag-cloud/blob/master/README.md#examples)

```jsx

<div className='app-outer'>
            <div className='app-inner'>
                    <TagCloud 
                            className='tag-cloud'
                       ...
                   </TagCloud>
           </div>
</div>
```

with this styling [(src)](https://stackblitz.com/edit/react-tag-cloud?file=style.css)

````css
.app-outer {
	align-items: center; 
	bottom: 0;
	display: flex;
	flex-direction: column;
	justify-content: center;
	left: 0;
	padding: 20px 0;
	position: absolute;
	right: 0;
	top: 0;
}

.app-inner {
	display: flex;
	flex-direction: column;
	height: 100%;
	max-width: 1000px;
	width: 100%;
}

 .tag-cloud {
	flex: 1;
}
````

See the complete example here: [(Playground on StackBlitz)](https://stackblitz.com/edit/react-tag-cloud?file=App.js) [(source)](./examples/tagCloud/src/App.js) 

I think I could be a good idea to include de css in the module to help the integration.

Hope it help both of you in case you haven't figured the solution already 🙂
